sudo: required

services:
    - docker

before_install:
    - make docker-pull

script:
    - make docker-test

notifications:
  email:
    on_success: change
    on_failure: always

after_success:
   - test $TRAVIS_BRANCH != 'master' && make trigger-build TOKEN=$OBS_TEST_TOKEN
   - test $TRAVIS_BRANCH == 'master' && make trigger-build TOKEN=$OBS_RELEASE_TOKEN
